version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"   # REST API
      - "6334:6334"   # gRPC
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      QDRANT__SERVICE__GRPC_PORT: 6334
      QDRANT__SERVICE__HTTP_PORT: 6333

  qdrant-init:
    image: curlimages/curl:latest
    depends_on:
      - qdrant
    entrypoint: >
      sh -c "
        sleep 5 &&
        curl -X PUT 'http://qdrant:6333/collections/products' -H 'Content-Type: application/json' -d '{\"vectors\": {\"size\": 4, \"distance\": \"Cosine\"}}'
      "

volumes:
  qdrant_data: