// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/concurrent": {
            "get": {
                "description": "Demonstrates concurrent processing with goroutines",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "performance"
                ],
                "summary": "Concurrent Processing Demo",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Number of items to process",
                        "name": "count",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        },
        "/api/health": {
            "get": {
                "description": "Returns API health status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        },
        "/api/leak": {
            "get": {
                "description": "Demonstrates a goroutine leak (use with caution)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "performance"
                ],
                "summary": "Goroutine Leak Demo",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Number of items to process",
                        "name": "count",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Should create a leak",
                        "name": "leak",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        },
        "/api/pool": {
            "get": {
                "description": "Demonstrates concurrent processing with a worker pool",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "performance"
                ],
                "summary": "Worker Pool Demo",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Number of items to process",
                        "name": "count",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of workers",
                        "name": "workers",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        },
        "/api/search": {
            "get": {
                "description": "Searching to keyword on vectorized db then populate it external services",
                "tags": [
                    "search"
                ],
                "summary": "Search Demo",
                "responses": {}
            }
        },
        "/api/sequential": {
            "get": {
                "description": "Demonstrates sequential processing",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "performance"
                ],
                "summary": "Sequential Processing Demo",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Number of items to process",
                        "name": "count",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "duration": {
                    "type": "string"
                },
                "endTime": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "startTime": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Go Bottlenecks API",
	Description:      "API for demonstrating Go performance bottlenecks",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
